# Generated by Django 5.2.5 on 2025-10-01 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sample_blog_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_prompts', models.JSONField(blank=True, default=list)),
                ('prompts_count', models.IntegerField(default=0)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blogs_general',
            },
        ),
    ]
