# Generated by Django 5.1.1 on 2025-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_bloggeneral_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneral',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for the blog post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Categories for taxonomy'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='html_content',
            field=models.TextField(blank=True, help_text='SEO-optimized HTML content', null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='is_ai_generated',
            field=models.BooleanField(default=True, help_text='Mark as AI-generated content for transparency'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the blog is published'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Publication date', null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='reading_time_minutes',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Whether search engines should index (noindex if False)'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='seo_keywords',
            field=models.JSONField(blank=True, default=list, help_text='SEO keywords array'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='Meta description (150-160 chars)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='seo_optimized',
            field=models.BooleanField(default=False, help_text='Whether SEO optimization has been applied'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='seo_slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO-optimized title (50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-LD structured data schemas'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization and internal linking'),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='twitter_card_type',
            field=models.CharField(default='summary_large_image', help_text='Twitter Card type', max_length=50),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Total word count'),
        ),
    ]
