# Generated by Django 5.1.1 on 2026-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0003_bloggeneral_canonical_url_bloggeneral_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneral',
            name='website_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
