# Generated by Django 5.1.1 on 2026-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0004_bloggeneral_website_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggeneral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='bloggeneral',
            table='blog_general',
        ),
    ]
