# Generated by Django 5.1.1 on 2025-10-17 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('session_id', models.CharField(default='', max_length=100)),
                ('context_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_conversation_context',
                'indexes': [models.Index(fields=['user_id', 'session_id'], name='chat_conver_user_id_618630_idx')],
                'unique_together': {('user_id', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='chat_sessio_user_id_5d5a12_idx'), models.Index(fields=['session_id'], name='chat_sessio_session_a3bcba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relevant_documents', models.JSONField(blank=True, default=list)),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('processing_time', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('session_id', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'), models.Index(fields=['message_type'], name='chat_messag_message_b8fb34_idx')],
            },
        ),
    ]
