# Generated by Django 5.2.5 on 2025-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_proposal_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworkproposal',
            name='contact_information',
            field=models.TextField(blank=True, help_text='Your contact details (email, phone, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='upworkproposal',
            name='upwork_profile_link',
            field=models.URLField(blank=True, help_text='Your Upwork profile URL', null=True),
        ),
        migrations.AddField(
            model_name='upworkproposal',
            name='your_name',
            field=models.CharField(blank=True, help_text='Your full name for the proposal signature', max_length=255, null=True),
        ),
    ]
