# Generated by Django 5.2.5 on 2025-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_proposal_generator', '0002_add_personal_info_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworkproposal',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the client contact person (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upworkproposal',
            name='company_name',
            field=models.CharField(blank=True, help_text="Name of the client's company (optional)", max_length=255, null=True),
        ),
    ]
