# Generated by Django 5.1.1 on 2025-10-17 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_proposal_generator', '0003_alter_upworkproposal_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upworkproposal',
            name='user',
        ),
        migrations.AddField(
            model_name='upworkproposal',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='upworkproposal',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upworkproposal',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='upworkproposal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='upworkproposal',
            index=models.Index(fields=['user_id', 'created_at'], name='upwork_prop_user_id_d6c6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='upworkproposal',
            index=models.Index(fields=['status'], name='upwork_prop_status_afa8c0_idx'),
        ),
    ]
