# Generated by Django 5.1.1 on 2025-10-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork_proposal_generator', '0005_upworkproposal_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworkproposal',
            name='use_knowledge_base',
            field=models.BooleanField(default=True, help_text='Whether to use knowledge base for relevant project examples'),
        ),
    ]
