# Generated by Django 5.2.5 on 2025-10-01 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_posts',
            },
        ),
        migrations.CreateModel(
            name='LinkedinPostingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('linkedin_username', models.CharField(default='', max_length=150)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('post_status', models.CharField(default='success', max_length=50)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('images_count', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_posting_content',
            },
        ),
        migrations.CreateModel(
            name='LinkedinAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('posts_analytics', models.JSONField(default=list)),
                ('total_reactions', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_reposts', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_analytics',
                'unique_together': {('user_id', 'linkedin_profile_id')},
            },
        ),
    ]
