# Generated by Django 5.1.1 on 2025-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_post_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinanalytics',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinanalytics',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpostingcontent',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpostingcontent',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
    ]
