# Generated by Django 5.2.5 on 2025-10-02 12:49

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('linkedin_username', models.CharField(default='', max_length=150)),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('images_count', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='text', max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('user_timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('posted', 'Posted'), ('partially_posted', 'Partially Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedule_posts',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
