# Generated by Django 5.1.1 on 2026-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('hashed_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog API Key',
                'verbose_name_plural': 'Blog API Keys',
                'db_table': 'blog_api_key',
            },
        ),
    ]
