# Generated by Django 4.2.21 on 2025-05-27 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAiNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('news_date', models.DateField()),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blogs_ai_news',
            },
        ),
        migrations.CreateModel(
            name='BlogGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sample_blog_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blogs_general',
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'image_generation',
            },
        ),
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_posts',
            },
        ),
        migrations.CreateModel(
            name='TrendingTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('rising_topics', models.JSONField(default=list)),
                ('top_topics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'trending_topics',
            },
        ),
        migrations.CreateModel(
            name='LinkedinAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('posts_analytics', models.JSONField(default=list)),
                ('total_reactions', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_reposts', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_analytics',
                'unique_together': {('user_id', 'linkedin_profile_id')},
            },
        ),
    ]
