# Generated by Django 4.2.21 on 2025-05-26 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('posts_analytics', models.JSONField(default=list)),
                ('total_reactions', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_reposts', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_analytics',
                'unique_together': {('user_id', 'linkedin_profile_id')},
            },
        ),
    ]
