# Generated by Django 4.2.21 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneral',
            name='image_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bloggeneral',
            name='prompts_count',
            field=models.IntegerField(default=0),
        ),
    ]
