# Generated by Django 4.2.21 on 2025-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bloggeneral_image_prompts_bloggeneral_prompts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='enhanced_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='generation_method',
            field=models.CharField(default='sora_style', max_length=50),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='image_style',
            field=models.CharField(default='professional_cinematic', max_length=50),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='images_count',
            field=models.IntegerField(default=1),
        ),
    ]
