# Generated by Django 4.2.21 on 2025-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_linkedinanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggeneral',
            name='sample_blog_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
