# Generated by Django 4.2.21 on 2025-06-04 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagegeneration_enhanced_prompts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPostingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('linkedin_profile_id', models.CharField(max_length=255)),
                ('linkedin_username', models.CharField(default='', max_length=150)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('post_status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'linkedin_posting_content',
            },
        ),
    ]
