# Generated by Django 5.2.3 on 2025-07-14 11:34

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_schedule_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('prompt', models.TextField()),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_image', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('enhanced_prompt', models.TextField(blank=True, default='')),
                ('edit_status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'image_editing',
            },
        ),
        migrations.AddField(
            model_name='blogainews',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scheduleposts',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scheduleposts',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('posted', 'Posted'), ('partially_posted', 'Partially Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
