# Generated by Django 5.2.5 on 2025-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bloggeneral_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggeneral',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='generation_method',
            field=models.CharField(default='flux', max_length=50),
        ),
    ]
