# Generated by Django 5.2.5 on 2025-09-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatsession_pdfdocument_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='title',
        ),
    ]
