# Generated by Django 5.2.5 on 2025-10-02 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('prompt', models.TextField()),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_image', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('enhanced_prompt', models.TextField(blank=True, default='')),
                ('edit_status', models.CharField(default='success', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'image_editing',
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('images_count', models.IntegerField(default=1)),
                ('enhanced_prompts', models.JSONField(blank=True, default=list)),
                ('generation_method', models.CharField(default='flux', max_length=50)),
                ('image_style', models.CharField(default='professional_cinematic', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'image_generation',
            },
        ),
    ]
