# Generated by Django 5.1.1 on 2025-10-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_imageediting_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegeneration',
            name='image_url',
        ),
    ]
