# Generated by Django 5.2.5 on 2025-10-01 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('md', 'Markdown'), ('txt', 'Text File')], max_length=10)),
                ('content', models.TextField()),
                ('uploaded_url', models.URLField(max_length=500)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting Content'), ('indexing', 'Indexing to Pinecone'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('pinecone_indexed', models.BooleanField(default=False)),
                ('pinecone_index_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pdf_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
