# Generated by Django 5.1.1 on 2025-10-23 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Directories',
                'db_table': 'knowledge_base_directories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='pinecone_namespace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='directory',
            field=models.ForeignKey(blank=True, help_text='Directory where this document is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.directory'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['directory', '-created_at'], name='pdf_documen_directo_1aa969_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['user_id', 'directory'], name='pdf_documen_user_id_3d1e72_idx'),
        ),
    ]
