# Generated by Django 5.1.1 on 2025-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_directory_pdfdocument_pinecone_namespace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('name', 'organization_id')},
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['organization_id', 'name'], name='knowledge_b_organiz_c9dda7_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['organization_name', 'name'], name='knowledge_b_organiz_ee8729_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['organization_id', 'directory'], name='pdf_documen_organiz_58ee0e_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['organization_name', 'directory'], name='pdf_documen_organiz_e588b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['organization_id', '-created_at'], name='pdf_documen_organiz_6dd0a6_idx'),
        ),
    ]
