# Generated by Django 5.1.1 on 2025-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_directory_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='loom_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
