# Generated by Django 5.1.1 on 2026-01-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_generator', '0005_alter_bloggeneral_created_at_alter_bloggeneral_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Unique session identifier (UUID)', max_length=255, unique=True)),
                ('ip_hash', models.CharField(help_text='Hashed IP address for privacy-safe uniqueness tracking', max_length=64)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pixel_load', 'Pixel Load (Initial View)'), ('heartbeat', 'Heartbeat (Active Reading)'), ('scroll', 'Scroll Depth Update'), ('visibility', 'Page Visibility Change')], max_length=20)),
                ('scroll_percent', models.IntegerField(default=0, help_text='Percentage of page scrolled')),
                ('time_delta_ms', models.IntegerField(default=0, help_text='Time elapsed since last heartbeat in ms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='blog_generator.bloggeneral')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.analyticsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('engaged_reads', models.PositiveIntegerField(default=0)),
                ('avg_scroll_depth', models.FloatField(default=0.0, help_text='Average scroll depth percentage')),
                ('avg_time_on_page_sec', models.FloatField(default=0.0, help_text='Average time on page in seconds')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_aggregate', to='blog_generator.bloggeneral')),
            ],
        ),
    ]
