# Generated by Django 4.2.21 on 2025-05-22 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        # Removed duplicated fields (groups, is_active, is_staff, is_superuser, last_login, user_permissions)
        # that were already added in 0001_initial.py
        # Only keeping the field alterations that are unique to this migration
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
