# Generated by Django 5.1.1 on 2025-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization display name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, help_text='User role in organization', max_length=100, null=True),
        ),
    ]
