# Generated by Django 4.2.21 on 2025-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_access_token',
            field=models.TextField(blank=True, help_text='LinkedIn OAuth access token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile_id',
            field=models.CharField(blank=True, help_text='LinkedIn profile ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When LinkedIn token expires', null=True),
        ),
    ]
