# Generated by Django 5.1.1 on 2025-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Clerk organization IDs user belongs to'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_names',
            field=models.JSONField(blank=True, default=list, help_text='List of organization display names (slugs)'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of user roles in each organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_id',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Primary organization ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Primary organization name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_role',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Primary organization role', max_length=100, null=True),
        ),
    ]
