# Generated by Django 5.2.5 on 2025-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_jwt_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_user_id',
            field=models.CharField(blank=True, help_text='Clerk user ID', max_length=100, null=True),
        ),
    ]
