# Generated by Django 5.1.1 on 2025-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopics',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='trendingtopics',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingtopics',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='trendingtopics',
            index=models.Index(fields=['user_id', 'created_at'], name='trending_to_user_id_3a4700_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingtopics',
            index=models.Index(fields=['keyword'], name='trending_to_keyword_4deac7_idx'),
        ),
    ]
