# Generated by Django 5.1.1 on 2025-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_trends', '0002_trendingtopics_email_trendingtopics_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingtopics',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Clerk organization ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trendingtopics',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name/slug', max_length=255, null=True),
        ),
    ]
